jdk: 'JDK 1.7'
jobs:
  pr-build: '%(name)s-PRs'
  branch-build: '%(name)s-%(branch)s'
pr-build:
  name: '%(name)s-PRs'
  template: pr-build.xml
  build-command: '-B -X -V -T4 clean verify -Prun-its -Pci'
branches:
  - name: master
    template: branch-build.xml
    build-command: '-B -X -V -T4 clean deploy -Prun-its -Pci'
